package com.yiyekeji.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yiyekeji.dao.SaveMessage;

import com.yiyekeji.dao.SaveMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig saveMessageDaoConfig;

    private final SaveMessageDao saveMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        saveMessageDaoConfig = daoConfigMap.get(SaveMessageDao.class).clone();
        saveMessageDaoConfig.initIdentityScope(type);

        saveMessageDao = new SaveMessageDao(saveMessageDaoConfig, this);

        registerDao(SaveMessage.class, saveMessageDao);
    }
    
    public void clear() {
        saveMessageDaoConfig.getIdentityScope().clear();
    }

    public SaveMessageDao getSaveMessageDao() {
        return saveMessageDao;
    }

}
