package com.yiyekeji.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import com.yiyekeji.impl.IInformation;

/**
 * Entity mapped to table "CHAT_MESSAGE".
 */
public class ChatMessage implements Parcelable,Cloneable,IInformation {

    private Long id;
    private String msgId;
    private String senderId;
    private String receiverId;
    private String groupId;
    private String messageType;
    private String content;
    private String date;
    private String sendStatus;
    private String senderName;
    private String receiverName;
    private String isReceiver;
    private String owner;

    public ChatMessage() {
    }

    public ChatMessage(Long id) {
        this.id = id;
    }

    public ChatMessage(Long id, String msgId, String senderId, String receiverId, String groupId, String messageType, String content, String date, String sendStatus, String senderName, String receiverName, String isReceiver, String owner) {
        this.id = id;
        this.msgId = msgId;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.groupId = groupId;
        this.messageType = messageType;
        this.content = content;
        this.date = date;
        this.sendStatus = sendStatus;
        this.senderName = senderName;
        this.receiverName = receiverName;
        this.isReceiver = isReceiver;
        this.owner = owner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsgId() {
        return msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }


    @Override
    public String getMain() {
        return content;
    }
    @Override
    public String getDate() {
        return date;
    }

    @Override
    public String getOtherSide() {
        if (isReceiver.equals("1")) {
            return senderName;
        } else {
            return receiverName;
        }
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getSendStatus() {
        return sendStatus;
    }

    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus;
    }

    public String getSenderName() {
        return senderName;
    }

    public void setSenderName(String senderName) {
        this.senderName = senderName;
    }

    public String getReceiverName() {
        return receiverName;
    }

    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    public String getIsReceiver() {
        return isReceiver;
    }

    public void setIsReceiver(String isReceiver) {
        this.isReceiver = isReceiver;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.msgId);
        dest.writeString(this.senderId);
        dest.writeString(this.receiverId);
        dest.writeString(this.groupId);
        dest.writeString(this.messageType);
        dest.writeString(this.content);
        dest.writeString(this.date);
        dest.writeString(this.sendStatus);
        dest.writeString(this.senderName);
        dest.writeString(this.receiverName);
        dest.writeString(this.isReceiver);
        dest.writeString(this.owner);
    }

    protected ChatMessage(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.msgId = in.readString();
        this.senderId = in.readString();
        this.receiverId = in.readString();
        this.groupId = in.readString();
        this.messageType = in.readString();
        this.content = in.readString();
        this.date = in.readString();
        this.sendStatus = in.readString();
        this.senderName = in.readString();
        this.receiverName = in.readString();
        this.isReceiver = in.readString();
        this.owner = in.readString();
    }

    public static final Creator<ChatMessage> CREATOR = new Creator<ChatMessage>() {
        @Override
        public ChatMessage createFromParcel(Parcel source) {
            return new ChatMessage(source);
        }

        @Override
        public ChatMessage[] newArray(int size) {
            return new ChatMessage[size];
        }
    };
}
