package com.yiyekeji.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yiyekeji.dao.ChatMessage;
import com.yiyekeji.dao.Session;

import com.yiyekeji.dao.ChatMessageDao;
import com.yiyekeji.dao.SessionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMessageDaoConfig;
    private final DaoConfig sessionDaoConfig;

    private final ChatMessageDao chatMessageDao;
    private final SessionDao sessionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);

        registerDao(ChatMessage.class, chatMessageDao);
        registerDao(Session.class, sessionDao);
    }
    
    public void clear() {
        chatMessageDaoConfig.getIdentityScope().clear();
        sessionDaoConfig.getIdentityScope().clear();
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

}
