package com.yiyekeji.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yiyekeji.dao.SendMessage;
import com.yiyekeji.dao.ReceiveMessage;

import com.yiyekeji.dao.SendMessageDao;
import com.yiyekeji.dao.ReceiveMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sendMessageDaoConfig;
    private final DaoConfig receiveMessageDaoConfig;

    private final SendMessageDao sendMessageDao;
    private final ReceiveMessageDao receiveMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sendMessageDaoConfig = daoConfigMap.get(SendMessageDao.class).clone();
        sendMessageDaoConfig.initIdentityScope(type);

        receiveMessageDaoConfig = daoConfigMap.get(ReceiveMessageDao.class).clone();
        receiveMessageDaoConfig.initIdentityScope(type);

        sendMessageDao = new SendMessageDao(sendMessageDaoConfig, this);
        receiveMessageDao = new ReceiveMessageDao(receiveMessageDaoConfig, this);

        registerDao(SendMessage.class, sendMessageDao);
        registerDao(ReceiveMessage.class, receiveMessageDao);
    }
    
    public void clear() {
        sendMessageDaoConfig.getIdentityScope().clear();
        receiveMessageDaoConfig.getIdentityScope().clear();
    }

    public SendMessageDao getSendMessageDao() {
        return sendMessageDao;
    }

    public ReceiveMessageDao getReceiveMessageDao() {
        return receiveMessageDao;
    }

}
