package com.yiyekeji.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SAVE_MESSAGE".
 */
public class SaveMessage {

    private String id;
    private String senderId;
    private String receiverId;
    private Boolean isReceiver;
    private String groupId;
    private String messageType;
    private String content;
    private String date;

    public SaveMessage() {
    }

    public SaveMessage(String id, String senderId, String receiverId, Boolean isReceiver, String groupId, String messageType, String content, String date) {
        this.id = id;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.isReceiver = isReceiver;
        this.groupId = groupId;
        this.messageType = messageType;
        this.content = content;
        this.date = date;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public Boolean getIsReceiver() {
        return isReceiver;
    }

    public void setIsReceiver(Boolean isReceiver) {
        this.isReceiver = isReceiver;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

}
